name: Workshop
version: 1.1.2
description: Create, edit, and delete content from the front-end of your site.
url: https://docs.statamic.com/workshop
developer: Statamic
developer_url: https://statamic.com
commercial: true
